### ISSUE TITLE
Regarding upgrading Chrome version in Circle CI

### ISSUE THREAD

**Issue by anubhavsinha98** [jottr/themes#1]
Hi @jottr, this is basically not an issue. I just saw your gist to update the Chrome version mentioned [here](https://gist.github.com/jottr/486764069d795e9e18d942d28b6cec7c).

I need help regarding it, I tried & updated the chrome version by using the above-mentioned script & I was getting the same error that older version of chrome is found so to check I made a job which checked chrome version installed in the environment of circle ci. The job runs ```google-chrome --version```, and the version which came as output was not the latest one rather it was 64.XX. The script although executed well without any error, but how the version of the chrome was not the latest one. Do we need to do anything else other than just running the script? If yes, can you help me?

**Comment by jottr** [comment]
@anubhavsinha98 this is not related to this project.
